name: Publish Package

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    # Since the trigger is "release", this will check out the respective tag.
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run publish
      
